### ISSUE TITLE
Error 500 when creating listing

### ISSUE THREAD

**Issue by MeridianGH** [mninc/pytf#1]
I alwas get an error 500 when I try to execute my code. It looks like this:

    item = id
    price = {"metal": float(get_key_price()[1])}
    data = pytf2.bp_create_listing_create_data(intent=1, currencies=price, item_or_id=item, details='')
    listing = pytf2.bp_create_listing(listings=data, parse=True)

The error message looks as follows:

    Traceback (most recent call last):
      File "MyFilePath", line 76, in <module>
        main()
      File "MyFilePath", line 40, in main
        listing = pytf2.bp_create_listing(listings=data, parse=True)
      File "__init__.py Path", line 521, in bp_create_listing
        response = self.request("POST", "https://backpack.tf/api/classifieds/list/v1", params=data, param_method="json")
      File "__init__.py Path", line 49, in sync_request
        raise exceptions.BadStatusError(url, response.status_code, response.text)
    pytf2.exceptions.BadStatusError: https://backpack.tf/api/classifieds/list/v1 returned the bad status code 500`

I'd appreciate any help because I can't figure this out. Thanks in advance!

**Comment by mninc** [comment]
`bp_create_listing(self, listings: list, parse: bool=True)`

* **listings** - an array of listings to create

You should pass `[data]` to this method as it has to be an array of listings.

```py
item = id
price = {"metal": float(get_key_price()[1])}
data = pytf2.bp_create_listing_create_data(intent=1, currencies=price, item_or_id=item, details='')
listing = pytf2.bp_create_listing(listings=[data], parse=True)
```

If you get more errors, it could be useful to catch the error and look at it's properties. Most errors will have some properties with more information for debugging, such as the response from backpack.tf.

**Comment by MeridianGH** [comment]
Ohh. Didn't notice that the argument has to be an array. I thought the dictionary that data already is was meant. Thanks for helping out and providing this library. It helps me a lot!
